import Foundation

struct ShortcutStore {
    private enum AppScope {
        static let finder = "com.apple.finder"
        static let safari = "com.apple.Safari"
    }

    static let seedShortcuts: [ShortcutItem] = [
        // Core system and common actions (Apple Support: 102650)
        .init(keys: ["cmd", "x"], desc: "剪切", usageCount: 10),
        .init(keys: ["cmd", "c"], desc: "拷贝", usageCount: 10),
        .init(keys: ["cmd", "v"], desc: "粘贴", usageCount: 10),
        .init(keys: ["cmd", "z"], desc: "撤销", usageCount: 10),
        .init(keys: ["cmd", "shift", "z"], desc: "重做", usageCount: 9),
        .init(keys: ["cmd", "a"], desc: "全选", usageCount: 9),
        .init(keys: ["cmd", "f"], desc: "查找", usageCount: 9),
        .init(keys: ["cmd", "g"], desc: "查找下一个", usageCount: 8),
        .init(keys: ["cmd", "shift", "g"], desc: "查找上一个", usageCount: 7),
        .init(keys: ["cmd", "h"], desc: "隐藏当前 App", usageCount: 8),
        .init(keys: ["cmd", "opt", "h"], desc: "隐藏其他 App", usageCount: 7),
        .init(keys: ["cmd", "m"], desc: "最小化窗口", usageCount: 8),
        .init(keys: ["cmd", "opt", "m"], desc: "最小化所有窗口", usageCount: 6),
        .init(keys: ["cmd", "o"], desc: "打开", usageCount: 8),
        .init(keys: ["cmd", "p"], desc: "打印", usageCount: 7),
        .init(keys: ["cmd", "s"], desc: "保存", usageCount: 9),
        .init(keys: ["cmd", "t"], desc: "新建标签页", usageCount: 8),
        .init(keys: ["cmd", "w"], desc: "关闭窗口", usageCount: 8),
        .init(keys: ["cmd", "opt", "w"], desc: "关闭全部窗口", usageCount: 6),
        .init(keys: ["cmd", "q"], desc: "退出 App", usageCount: 9),
        .init(keys: ["cmd", "opt", "esc"], desc: "强制退出窗口", usageCount: 7),
        .init(keys: ["cmd", "space"], desc: "Spotlight 搜索", usageCount: 10),
        .init(keys: ["cmd", "opt", "space"], desc: "Finder 中 Spotlight", usageCount: 7),
        .init(keys: ["cmd", "ctrl", "space"], desc: "Emoji 与符号", usageCount: 8),
        .init(keys: ["cmd", "ctrl", "f"], desc: "全屏开关", usageCount: 7),
        .init(keys: ["cmd", "tab"], desc: "切换到下一个 App", usageCount: 10),
        .init(keys: ["cmd", "`"], desc: "切换同一 App 的窗口", usageCount: 7),
        .init(keys: ["cmd", ","], desc: "打开设置/偏好设置", usageCount: 8),
        .init(keys: ["cmd", "ctrl", "q"], desc: "锁定屏幕", usageCount: 7),
        .init(keys: ["cmd", "shift", "q"], desc: "注销（需确认）", usageCount: 5),
        .init(keys: ["cmd", "opt", "shift", "q"], desc: "立即注销", usageCount: 4),

        // Finder and system shortcuts (Apple Support: 102650)
        .init(keys: ["cmd", "d"], desc: "复制文件", usageCount: 7, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "e"], desc: "推出磁盘/卷宗", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "i"], desc: "显示简介", usageCount: 7, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "r"], desc: "刷新/重新载入", usageCount: 7, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "j"], desc: "显示视图选项", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "k"], desc: "连接服务器", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "n"], desc: "新建窗口", usageCount: 8, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "n"], desc: "新建智能文件夹", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "n"], desc: "新建文件夹", usageCount: 8, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "ctrl", "n"], desc: "以所选项新建文件夹", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "c"], desc: "打开电脑窗口", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "d"], desc: "打开桌面文件夹", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "f"], desc: "打开最近项目", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "h"], desc: "打开个人文件夹", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "i"], desc: "打开 iCloud Drive", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "k"], desc: "打开网络窗口", usageCount: 4, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "l"], desc: "打开下载文件夹", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "o"], desc: "打开文稿文件夹", usageCount: 6, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "p"], desc: "显示/隐藏预览面板", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "r"], desc: "打开 AirDrop", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "t"], desc: "显示/隐藏标签栏", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "shift", "u"], desc: "打开实用工具文件夹", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "ctrl", "t"], desc: "添加到侧边栏", usageCount: 4, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "p"], desc: "显示/隐藏路径栏", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "s"], desc: "显示/隐藏边栏", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "/"], desc: "显示/隐藏状态栏", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "t"], desc: "显示/隐藏工具栏", usageCount: 4, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "v"], desc: "移动（粘贴并移除原文件）", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "y"], desc: "快速查看", usageCount: 7, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "opt", "y"], desc: "快速查看幻灯片", usageCount: 4, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "1"], desc: "图标视图", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "2"], desc: "列表视图", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "3"], desc: "分栏视图", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),
        .init(keys: ["cmd", "4"], desc: "画廊视图", usageCount: 5, category: .finder, appScopes: [AppScope.finder]),

        // Text editing and formatting shortcuts (Apple Support: 102650)
        .init(keys: ["cmd", "b"], desc: "加粗", usageCount: 6, category: .textEditing),
        .init(keys: ["cmd", "u"], desc: "下划线", usageCount: 5, category: .textEditing),
        .init(keys: ["cmd", "shift", "s"], desc: "另存为/复制文稿", usageCount: 5, category: .textEditing),
        .init(keys: ["cmd", "opt", "f"], desc: "跳转到搜索栏", usageCount: 5, category: .textEditing),
        .init(keys: ["cmd", "opt", "c"], desc: "拷贝样式", usageCount: 4, category: .textEditing),
        .init(keys: ["cmd", "opt", "i"], desc: "显示/隐藏检查器", usageCount: 4, category: .textEditing),
        .init(keys: ["cmd", "opt", "shift", "v"], desc: "粘贴并匹配样式", usageCount: 6, category: .textEditing),
        .init(keys: ["opt", "delete"], desc: "删除左侧一个单词", usageCount: 5, category: .textEditing),
        .init(keys: ["ctrl", "h"], desc: "删除左侧字符", usageCount: 4, category: .textEditing),
        .init(keys: ["ctrl", "d"], desc: "删除右侧字符", usageCount: 4, category: .textEditing),
        .init(keys: ["ctrl", "k"], desc: "剪切到段落末尾", usageCount: 3, category: .textEditing),
        .init(keys: ["ctrl", "a"], desc: "移动到行首", usageCount: 4, category: .textEditing),
        .init(keys: ["ctrl", "e"], desc: "移动到行尾", usageCount: 4, category: .textEditing),
        .init(keys: ["ctrl", "f"], desc: "向前移动一个字符", usageCount: 3, category: .textEditing),
        .init(keys: ["ctrl", "b"], desc: "向后移动一个字符", usageCount: 3, category: .textEditing),
        .init(keys: ["ctrl", "l"], desc: "光标居中到可视区域", usageCount: 2, category: .textEditing),
        .init(keys: ["ctrl", "p"], desc: "上移一行", usageCount: 3, category: .textEditing),
        .init(keys: ["ctrl", "n"], desc: "下移一行", usageCount: 3, category: .textEditing),
        .init(keys: ["ctrl", "o"], desc: "在后方插入新行", usageCount: 2, category: .textEditing),
        .init(keys: ["ctrl", "t"], desc: "交换相邻字符", usageCount: 2, category: .textEditing),

        // Common extra shortcuts (Apple Support: 102323)
        .init(keys: ["cmd", "shift", "3"], desc: "全屏截图", usageCount: 7, category: .screenshot),
        .init(keys: ["cmd", "shift", "4"], desc: "区域截图", usageCount: 7, category: .screenshot),
        .init(keys: ["cmd", "shift", "5"], desc: "截图与录屏控制", usageCount: 6, category: .screenshot),

        // Safari app-specific shortcuts
        .init(keys: ["cmd", "l"], desc: "定位地址栏", usageCount: 7, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "r"], desc: "重新载入网页", usageCount: 7, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "opt", "r"], desc: "重新载入并忽略缓存", usageCount: 5, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "["], desc: "后退", usageCount: 7, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "]"], desc: "前进", usageCount: 7, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "shift", "["], desc: "上一标签页", usageCount: 6, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "shift", "]"], desc: "下一标签页", usageCount: 6, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "opt", "1"], desc: "切换到第 1 个标签页", usageCount: 4, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "opt", "2"], desc: "切换到第 2 个标签页", usageCount: 4, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "opt", "3"], desc: "切换到第 3 个标签页", usageCount: 4, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "opt", "4"], desc: "切换到第 4 个标签页", usageCount: 4, category: .browser, appScopes: [AppScope.safari]),
        .init(keys: ["cmd", "shift", "t"], desc: "恢复关闭的标签页", usageCount: 6, category: .browser, appScopes: [AppScope.safari])
    ]
}
